name: Multischemase CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
    # Update package version and set up git
    - uses: actions/setup-node@master
    - name: Update package version and setup git
      run: |
        git config user.name "Actions User"
        git config user.email noreply@github.com]
        npm version patch
                
    # Publish to NPMJS
    - uses: actions/setup-node@master
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org/'
    - name: Publish to NPMJS
    - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@andremrezende"
          npm config list
          npm publish --access public 
    - env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
