name: Multischemase CI
on:
  push:
    branches:
      - master

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Get version
      - uses: martinbeentjes/npm-get-version-action@v1.0.0
      
      # Update package version and set up git
      # - uses: actions/setup-node@master
      # - name: Update package version and setup git
      #   run: |
      #     git config user.name "Actions User"
      #     git config user.email noreply@github.com]
      #     npm version patch
      # npm version ${{ steps.package-version.outputs.current-version}}$(date +%s)

      # Publish to NPMJS
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to NPMJS
        run: |
          npm i
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config list
          npm publish --access public 
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
